"use client";
import Link from "next/link";
import { useFinSyncSession } from "@/components/session/FinSyncSessionProvider";
import { Badge, Card, EmptyState, MetricCard, PageHeader } from "@/components/ui";
import { formatRupees } from "@/lib/formatters";
export function Dashboard() { const { session } = useFinSyncSession(); const analysis = session?.profile_analysis; const hasProfile = !!session?.profile_input; const simulation = session?.goal_simulation; if (!hasProfile) return <><PageHeader title="Overview" description="Your adaptive financial plan will come together here." /><EmptyState title="Build your Financial Digital Profile" description="Add your financial inputs to calculate transparent ratios, capacity, a FinSync score, and an ML pattern persona." action={<Link href="/profile" className="primary-button">Complete profile</Link>} /></>; if (!analysis) return <><PageHeader title="Overview" description="Your adaptive financial plan will come together here." /><EmptyState title="Analysis Pending" description="Your profile has been saved. The calculation engine will process it in a future phase." /></>;
const m = analysis.metrics; const persona = analysis.ml_persona; const activity = session?.proposals.filter((p) => p.status !== "pending").slice(-4).reverse() ?? []; return <><PageHeader title={`Welcome, ${''}`} description="Your current financial plan, calculated from the latest approved session state." action={<Link href="/assistant" className="secondary-button">Ask Companion</Link>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Financial Health Score" value={`${analysis.financial_health_score}/100`} note={analysis.health_label} /><MetricCard label="Net cash flow" value={formatRupees(m.net_cash_flow)} /><MetricCard label="Estimated capacity" value={formatRupees(m.estimated_monthly_investment_capacity)} /><MetricCard label="Net worth" value={formatRupees(m.net_worth)} note={m.emergency_fund_coverage_months === null ? "Coverage unavailable" : `${m.emergency_fund_coverage_months} months emergency coverage`} /></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><Badge tone="ml">Financial Persona ML</Badge><h2 className="mt-4 text-xl font-bold text-white">{persona.available ? persona.persona : "Persona unavailable"}</h2><p className="mt-2 text-sm leading-6 text-slate-500">Pattern context only. Deterministic calculations and safeguards remain authoritative.</p></Card><Card><Badge tone="success">Suggested strategy</Badge><h2 className="mt-4 text-xl font-bold text-white">{suggested(analysis)}</h2><p className="mt-2 text-sm leading-6 text-slate-500">Selected from reserve coverage, debt service, net worth, stability, horizon, and preferences.</p></Card></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><Card><div className="flex justify-between"><h2 className="font-bold text-white">Goal capacity</h2><Link href="/goals" className="text-sm text-emerald-300">View goals</Link></div>{simulation ? <><p className="mt-4 text-3xl font-bold text-white">{simulation.goals.length} goals</p><p className="mt-2 text-sm text-slate-500">Required {formatRupees(simulation.capacity_summary.total_required_contributions)} of {formatRupees(simulation.capacity_summary.estimated_monthly_capacity)} monthly capacity.</p>{simulation.capacity_summary.capacity_conflicts.length > 0 && <p className="mt-4 rounded-xl bg-amber-400/10 p-3 text-sm text-amber-200">Some goals are not fully funded within combined capacity.</p>}</> : <EmptyState title="No goal simulation yet" description="Create and simulate goals to see priority allocation and future projections." action={<Link href="/goals" className="primary-button">Create goals</Link>} />}</Card><Card><h2 className="font-bold text-white">Recent activity</h2>{activity.length ? <ul className="mt-4 space-y-3">{activity.map((p) => <li key={p.id} className="text-sm text-slate-400"><span className="capitalize text-slate-200">{p.status}</span> · {p.summary}</li>)}</ul> : <p className="mt-4 text-sm text-slate-500">No approved or rejected proposals in this session.</p>}</Card></div></>; }
function suggested(result: NonNullable<ReturnType<typeof useFinSyncSession>["session"]>["profile_analysis"]) { if (!result) return "Complete profile"; const m = result.metrics; if ((m.emergency_fund_coverage_months ?? 0) < 3 || (m.debt_service_ratio ?? 0) > .3 || m.net_worth < 0) return "Safety First"; return "Balanced Progress"; }


