"use client";

import { useCallback, useEffect, useState } from "react";
import { getMarketOverview, type MarketOverviewResponse, type MarketSnapshotItem } from "@/lib/marketData";

const freshnessLabel = (item: MarketSnapshotItem, age: number) => item.freshness === "cached" ? `Cached · updated ${Math.max(1, Math.floor(age / 60))} min ago` : item.freshness === "end_of_day" ? "End of day" : item.freshness.replaceAll("_", " ");
const time = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Unavailable";

export function MarketOverview() {
  const [data, setData] = useState<MarketOverviewResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await getMarketOverview()); } catch { setError("Market data temporarily unavailable."); } finally { setLoading(false); } }, []);
  useEffect(() => { getMarketOverview().then(setData).catch(() => setError("Market data temporarily unavailable.")).finally(() => setLoading(false)); }, []);
  if (loading && !data) return <div className="mb-6 h-40 animate-pulse rounded-2xl bg-white/[0.035]" />;
  if (!data) return <div className="mb-6 rounded-2xl border border-white/10 bg-white/[0.025] p-6"><p className="text-sm text-slate-300">{error}</p><button type="button" className="secondary-button mt-4" onClick={() => void load()}>Check for updates</button></div>;
  return <div className="mb-7 space-y-5">
    <section><div className="mb-3 flex items-end justify-between gap-3"><div><h3 className="text-lg font-bold text-white">Market snapshot</h3><p className="mt-1 text-xs text-slate-500">Fetched {time(data.fetched_at)} · cached for five minutes</p></div><button type="button" onClick={() => void load()} disabled={loading} className="secondary-button !px-3 !py-2 text-xs disabled:opacity-50">{loading ? "Checking…" : "Check for updates"}</button></div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{data.items.map(item => <Snapshot key={item.symbol} item={item} age={data.cache_age_seconds} />)}</div>
    </section>
    <div className="grid gap-5 lg:grid-cols-2">
      <section className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><h3 className="text-sm font-bold text-white">Why markets moved</h3><p className="mt-1 text-xs text-slate-500">Possible contributing factors—not proven causality.</p>{data.possible_factors.length ? <ul className="mt-4 space-y-3 text-xs leading-5 text-slate-400">{data.possible_factors.map(item => <li key={item}>• {item}</li>)}</ul> : <p className="mt-4 text-xs text-slate-500">Insufficient current data to identify notable movements.</p>}</section>
      <section className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><h3 className="text-sm font-bold text-white">Asset class pulse</h3><div className="mt-3 space-y-2">{data.items.filter(item => item.instrument !== "SENSEX").map(item => <div key={item.symbol} className="flex items-center justify-between gap-3 border-b border-white/5 py-2 text-xs"><span className="capitalize text-slate-400">{item.asset_class === "commodity" ? "Crude / commodities" : item.asset_class}</span><span className={item.change_percent == null ? "text-slate-500" : item.change_percent >= 0 ? "text-emerald-300" : "text-rose-300"}>{item.change_percent == null ? "Unavailable" : `${item.change_percent >= 0 ? "↑" : "↓"} ${Math.abs(item.change_percent).toFixed(2)}%`}</span></div>)}</div></section>
    </div>
    <section className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><h3 className="text-sm font-bold text-white">Market news and events</h3>{data.news.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{data.news.map((item, index) => <article key={`${item.headline}-${index}`} className="border-l-2 border-sky-400/30 pl-4"><div className="flex flex-wrap gap-2 text-[10px] uppercase tracking-wider text-slate-600"><span>{item.source}</span><span>·</span><span>{time(item.published_at)}</span><span>·</span><span>{item.affected_asset}</span></div>{item.url ? <a href={item.url} target="_blank" rel="noreferrer" className="mt-1 block text-sm font-semibold text-slate-200 hover:text-sky-300">{item.headline}</a> : <p className="mt-1 text-sm font-semibold text-slate-200">{item.headline}</p>}<p className="mt-1 text-xs leading-5 text-slate-500">{item.explanation}</p></article>)}</div> : <p className="mt-4 text-xs text-slate-500">No attributed market news is currently available. Nothing has been fabricated.</p>}</section>
    {error && <p className="text-xs text-amber-300">{error} Showing the last available response.</p>}
  </div>;
}

function Snapshot({ item, age }: { item: MarketSnapshotItem; age: number }) { const positive = (item.change_percent || 0) >= 0; return <article className="rounded-xl border border-white/10 bg-black/15 p-4"><div className="flex justify-between gap-2"><p className="text-xs font-bold text-slate-300">{item.instrument}</p><span className="text-[10px] text-slate-600">{item.symbol}</span></div>{item.value == null ? <p className="mt-3 text-sm text-slate-500">Unavailable</p> : <><p className="mt-3 text-xl font-bold tabular-nums text-white">{item.value.toLocaleString("en-IN", { maximumFractionDigits: 2 })}</p><p className={`mt-1 text-xs font-semibold ${positive ? "text-emerald-300" : "text-rose-300"}`}>{positive ? "+" : ""}{item.change?.toFixed(2)} · {positive ? "+" : ""}{item.change_percent?.toFixed(2)}%</p></>}<div className="mt-3 border-t border-white/5 pt-2 text-[10px] leading-4 text-slate-600"><p>{freshnessLabel(item, age)}</p><p>Market: {time(item.market_timestamp)}</p><p>{item.provider}</p></div></article>; }
