"use client";

import { useEffect, useState } from "react";
import { analyzeStock, searchStocks, type SearchResult, type StockAnalysisResponse } from "@/lib/marketData";

export function StockAnalyzer() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchResult[]>([]);
  const [selected, setSelected] = useState<SearchResult | null>(null); const [analysis, setAnalysis] = useState<StockAnalysisResponse | null>(null);
  const [searching, setSearching] = useState(false); const [analyzing, setAnalyzing] = useState(false); const [activeAgent, setActiveAgent] = useState(0); const [error, setError] = useState("");
  useEffect(() => {
    if (query.trim().length < 2 || selected?.name === query) return;
    const timer = setTimeout(() => { setSearching(true); searchStocks(query.trim()).then(setResults).catch(() => setResults([])).finally(() => setSearching(false)); }, 350);
    return () => clearTimeout(timer);
  }, [query, selected]);
  const choose = (stock: SearchResult) => { setSelected(stock); setQuery(stock.name); setResults([]); setAnalysis(null); setError(""); };
  const run = async () => {
    if (!selected) return; setAnalyzing(true); setActiveAgent(0); setError(""); setAnalysis(null);
    try { setAnalysis(await analyzeStock(selected.symbol)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Stock analysis failed."); } finally { setAnalyzing(false); }
  };
  return <section className="mb-8 rounded-3xl border border-emerald-400/20 bg-gradient-to-br from-emerald-400/[0.08] to-white/[0.02] p-6 sm:p-8">
    <p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Three-agent stock research</p>
    <div className="mt-3 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><h2 className="text-2xl font-bold text-white">Choose a stock to investigate</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Technical, fundamental, and risk agents independently score the available evidence before FinSync combines their findings.</p></div></div>
    <div className="relative mt-6 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><label htmlFor="stock-search" className="sr-only">Search stocks</label><input id="stock-search" value={query} onChange={event => { setQuery(event.target.value); setSelected(null); }} className="goal-input h-full" placeholder="Search company or symbol, e.g. RELIANCE" autoComplete="off" />{(results.length > 0 || searching) && <div className="absolute inset-x-0 top-[calc(100%+.4rem)] z-20 max-h-72 overflow-y-auto rounded-xl border border-white/10 bg-slate-900 p-1 shadow-2xl">{searching ? <p className="p-3 text-sm text-slate-500">Searching…</p> : results.map(stock => <button type="button" key={`${stock.symbol}-${stock.exchange}`} onClick={() => choose(stock)} className="flex w-full items-center justify-between gap-3 rounded-lg p-3 text-left hover:bg-white/5"><span><strong className="block text-sm text-white">{stock.name}</strong><small className="text-slate-500">{stock.symbol}</small></span><small className="text-slate-500">{stock.exchange}</small></button>)}</div>}</div><button type="button" onClick={() => void run()} disabled={!selected || analyzing} className="primary-button justify-center disabled:cursor-not-allowed disabled:opacity-40">{analyzing ? "Agents analyzing…" : "Analyze stock"}</button></div>
    {analyzing && <SequentialProgress active={activeAgent} advance={setActiveAgent} />}
    {error && <p className="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-200" role="alert">{error}</p>}
    {analysis && <AnalysisResult value={analysis} />}
  </section>;
}

function SequentialProgress({ active, advance }: { active: number; advance: (value: number) => void }) {
  const agents = ["Technical", "Fundamental", "Risk"];
  useEffect(() => { const timer = setTimeout(() => advance(Math.min(2, active + 1)), 1800); return () => clearTimeout(timer); }, [active, advance]);
  return <div className="mt-6" aria-live="polite"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-500">Sequential research pipeline</p><div className="grid gap-2 sm:grid-cols-[1fr_auto_1fr_auto_1fr] sm:items-center">{agents.map((label, index) => <div className="contents" key={label}><div className={`rounded-xl border p-4 ${index < active ? "border-emerald-400/20 bg-emerald-400/5" : index === active ? "border-sky-400/30 bg-sky-400/5" : "border-white/10 bg-black/10"}`}><div className="flex items-center gap-3"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${index < active ? "bg-emerald-400/15 text-emerald-300" : index === active ? "animate-pulse bg-sky-400/15 text-sky-300" : "bg-white/5 text-slate-600"}`}>{index < active ? "✓" : index + 1}</span><div><strong className={index <= active ? "text-sm text-slate-200" : "text-sm text-slate-600"}>{label} agent</strong><p className={`text-[11px] ${index < active ? "text-emerald-400" : index === active ? "text-sky-400" : "text-slate-700"}`}>{index < active ? "Complete" : index === active ? "Analyzing…" : "Waiting"}</p></div></div></div>{index < agents.length - 1 && <span className="hidden text-slate-700 sm:block">→</span>}</div>)}</div><p className="mt-3 text-xs text-slate-600">Each specialist runs after the previous stage; synthesis begins after the risk review.</p></div>;
}

function AnalysisResult({ value }: { value: StockAnalysisResponse }) {
  const stanceTone = value.stance === "favourable" ? "text-emerald-300" : value.stance === "cautious" ? "text-rose-300" : "text-amber-300";
  const evidenceBalance = value.stance === "favourable" ? "Positive" : value.stance === "cautious" ? "Cautious" : value.stance === "insufficient_data" ? "Insufficient data" : "Mixed";
  return <div className="mt-8 border-t border-white/10 pt-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-sm text-slate-500">{value.symbol} · {value.currency} {value.current_price.toLocaleString("en-IN", { maximumFractionDigits: 2 })}</p><h3 className="mt-1 text-2xl font-bold text-white">{value.company_name}</h3><p className={`mt-2 text-sm font-bold uppercase tracking-wider ${stanceTone}`}>Current evidence balance: {evidenceBalance}</p></div><div className="grid grid-cols-3 gap-2 text-center"><Score label="Composite evidence" value={value.overall_score} tone="emerald" help="Weighted technical, fundamental, and inverse-risk evidence; not expected return." /><Score label="Observed risk" value={value.risk_score} tone="rose" help="Higher means more observed volatility, drawdown, beta, leverage, or adverse context." /><Score label="Data confidence" value={value.confidence} tone="sky" help="Input coverage and agreement—not the probability that the stock rises." /></div></div>
    <p className="mt-5 max-w-4xl text-sm leading-6 text-slate-300">{value.summary}</p>
    <PriceChart points={value.price_history} currency={value.currency} />
    <div className="mt-5 grid gap-3 lg:grid-cols-3">{value.agents.map(agent => <article key={agent.agent} className="rounded-xl border border-white/10 bg-black/15 p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{agent.label} agent</p><p className="text-xl font-bold text-white">{agent.score}%</p></div><Meter value={agent.score} tone="emerald" label={`${agent.label} score`} /><p className="mt-3 text-xs leading-5 text-slate-400">{agent.summary}</p><div className="mt-3 flex justify-between text-[11px] text-slate-600"><span>Evidence confidence</span><span>{agent.confidence}%</span></div><Meter value={agent.confidence} tone="sky" label={`${agent.label} confidence`} /><details className="mt-3 border-t border-white/10 pt-3"><summary className="cursor-pointer text-xs font-semibold text-sky-300">Evidence details</summary><EvidenceRows items={agent.evidence} /></details></article>)}</div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><List title="Supporting observations" items={value.advantages} tone="text-emerald-300" /><List title="Risk observations" items={value.concerns} tone="text-rose-300" /></div>
    <details className="mt-5 disclosure"><summary><span><strong className="text-sm">Analysis limitations</strong><small>{value.data_source} · market context: {value.market_regime || "unavailable"}</small></span><span className="text-xl text-slate-500">+</span></summary><ul className="space-y-2 border-t border-white/10 p-5 text-xs leading-5 text-slate-500">{value.limitations.map(item => <li key={item}>• {item}</li>)}</ul></details>
  </div>;
}
function Score({ label, value, tone, help }: { label: string; value: number; tone: "emerald" | "rose" | "sky"; help: string }) { const color = tone === "rose" ? "#fb7185" : tone === "sky" ? "#38bdf8" : "#34d399"; return <div className="min-w-20 rounded-xl bg-black/20 p-3" title={help}><div className="relative mx-auto grid h-14 w-14 place-items-center rounded-full" style={{ background: `conic-gradient(${color} ${value * 3.6}deg, rgb(255 255 255 / .08) 0)` }}><div className="absolute inset-1.5 rounded-full bg-slate-950" /><strong className="relative text-sm text-white">{value}%</strong></div><span className="mt-2 block text-[10px] uppercase leading-4 text-slate-500">{label}</span><span className="mt-1 block text-[9px] leading-3 text-slate-700">{help}</span></div>; }
function Meter({ value, tone, label }: { value: number; tone: "emerald" | "sky"; label: string }) { return <div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[0.07]" role="progressbar" aria-label={label} aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><div className={`h-full rounded-full ${tone === "sky" ? "bg-sky-400" : "bg-emerald-400"}`} style={{ width: `${value}%` }} /></div>; }
function PriceChart({ points, currency }: { points: { date: string; close: number }[]; currency: string }) {
  if (points.length < 2) return null;
  const width = 720, height = 170, left = 52, right = 12, top = 18, bottom = 30;
  const values = points.map(point => point.close), min = Math.min(...values), max = Math.max(...values), range = max - min || 1;
  const coords = points.map((point, index) => `${left + index / (points.length - 1) * (width - left - right)},${top + (max - point.close) / range * (height - top - bottom)}`).join(" ");
  const positive = points.at(-1)!.close >= points[0].close;
  return <figure className="mt-7 rounded-2xl border border-white/10 bg-black/15 p-4 sm:p-5"><div className="mb-3 flex items-end justify-between gap-3"><div><h4 className="text-sm font-bold text-white">One-year price history</h4><p className="mt-1 text-xs text-slate-500">Adjusted closing price · {currency}</p></div><p className={`text-sm font-bold ${positive ? "text-emerald-300" : "text-rose-300"}`}>{((points.at(-1)!.close / points[0].close - 1) * 100).toFixed(1)}%</p></div><svg viewBox={`0 0 ${width} ${height}`} className="h-auto w-full" role="img" aria-label={`One-year adjusted closing price from ${points[0].close} to ${points.at(-1)!.close} ${currency}`}><defs><linearGradient id="price-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={positive ? "#34d399" : "#fb7185"} stopOpacity=".28"/><stop offset="1" stopColor={positive ? "#34d399" : "#fb7185"} stopOpacity="0"/></linearGradient></defs>{[0, .5, 1].map(position => { const y = top + position * (height - top - bottom); const label = max - position * range; return <g key={position}><line x1={left} x2={width-right} y1={y} y2={y} stroke="rgb(255 255 255 / .08)"/><text x={left-8} y={y+4} textAnchor="end" fill="#64748b" fontSize="11">{label.toFixed(0)}</text></g>; })}<polygon points={`${left},${height-bottom} ${coords} ${width-right},${height-bottom}`} fill="url(#price-area)"/><polyline points={coords} fill="none" stroke={positive ? "#34d399" : "#fb7185"} strokeWidth="2.5" strokeLinejoin="round"/><text x={left} y={height-8} fill="#64748b" fontSize="11">{points[0].date.slice(0,7)}</text><text x={width-right} y={height-8} textAnchor="end" fill="#64748b" fontSize="11">{points.at(-1)!.date.slice(0,7)}</text></svg></figure>;
}
function List({ title, items, tone }: { title: string; items: string[]; tone: string }) { return <div className="rounded-xl bg-black/15 p-5"><h4 className={`text-sm font-bold ${tone}`}>{title}</h4>{items.length ? <ul className="mt-3 space-y-2 text-xs leading-5 text-slate-400">{items.map(item => <li key={item}>• {item}</li>)}</ul> : <p className="mt-3 text-xs text-slate-600">No supported items identified.</p>}</div>; }
function EvidenceRows({ items }: { items: string[] }) { return <dl className="mt-3 space-y-2">{items.map(item => { const [label, ...rest] = item.split(":"); return <div key={item} className="flex justify-between gap-3 text-xs"><dt className="text-slate-500">{label}</dt><dd className="text-right font-medium text-slate-300">{rest.join(":").trim() || "Available"}</dd></div>; })}</dl>; }
