"use client";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import { formatRupees } from "@/lib/formatters";
import type { GoalInput, GoalSimulationResponse, ScenarioAssumptions } from "@/types/goals";
import { GoalEditor } from "./GoalEditor";
import { GoalResultCard } from "./GoalResultCard";

const DEFAULT_ASSUMPTIONS: ScenarioAssumptions = { conservative: { nominal_annual_return: 4, annual_volatility: 8, inflation_rate: 6 }, base: { nominal_annual_return: 8, annual_volatility: 15, inflation_rate: 5 }, optimistic: { nominal_annual_return: 12, annual_volatility: 22, inflation_rate: 4 } };
const DEMO_GOALS: GoalInput[] = [
  { id: "vehicle-demo", name: "Vehicle", category: "vehicle", target_amount: 800000, amount_basis: "today_value", current_saved: 100000, horizon_months: 48, priority: "high", flexibility: "somewhat_flexible", planned_monthly_contribution: 12000, annual_step_up_percentage: 5 },
  { id: "house-demo", name: "House deposit", category: "house", target_amount: 4000000, amount_basis: "today_value", current_saved: 500000, horizon_months: 120, priority: "high", flexibility: "somewhat_flexible", planned_monthly_contribution: 20000, annual_step_up_percentage: 8 },
  { id: "wealth-demo", name: "Long-term wealth", category: "wealth_creation", target_amount: 10000000, amount_basis: "future_value", current_saved: 300000, horizon_months: 240, priority: "medium", flexibility: "flexible", planned_monthly_contribution: 15000, annual_step_up_percentage: 10 },
];

export function GoalPlanner({ initialCapacity }: { initialCapacity: number }) {
  const [capacity, setCapacity] = useState(Math.max(0, initialCapacity));
  const [goals, setGoals] = useState<GoalInput[]>(DEMO_GOALS);
  const [assumptions, setAssumptions] = useState<ScenarioAssumptions>(DEFAULT_ASSUMPTIONS);
  const [monteCarlo, setMonteCarlo] = useState(true);
  const [simulationCount, setSimulationCount] = useState(1000);
  const [result, setResult] = useState<GoalSimulationResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const submit = async (event: FormEvent) => {
    event.preventDefault(); setLoading(true); setError("");
    try {
      const baseUrl = (process.env.NEXT_PUBLIC_API_URL ?? "http://127.0.0.1:8000").replace(/\/$/, "");
      const response = await fetch(`${baseUrl}/api/v1/goals/simulate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ estimated_monthly_capacity: capacity, goals, assumptions, monte_carlo_enabled: monteCarlo, simulation_count: simulationCount, seed: 20260830 }) });
      if (!response.ok) { const body: unknown = await response.json().catch(() => null); throw new Error(apiError(body)); }
      setResult((await response.json()) as GoalSimulationResponse); window.scrollTo({ top: 0, behavior: "smooth" });
    } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Goal simulation failed."); }
    finally { setLoading(false); }
  };
  const updateGoal = (index: number, goal: GoalInput) => setGoals((current) => current.map((item, itemIndex) => itemIndex === index ? goal : item));
  const addGoal = () => setGoals((current) => [...current, { id: `goal-${Date.now()}`, name: "New goal", category: "custom", target_amount: 500000, amount_basis: "today_value", current_saved: 0, horizon_months: 60, priority: "medium", flexibility: "somewhat_flexible", planned_monthly_contribution: 5000, annual_step_up_percentage: 5 }]);

  return <div className="mx-auto w-full max-w-6xl"><header className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Link href="/onboarding" className="text-sm font-semibold text-emerald-300">← Financial profile</Link><p className="eyebrow mt-5">Deterministic goal planning</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-white sm:text-5xl">Turn goals into testable plans.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Compare scenarios, adjust timelines and contributions, and see how multiple goals fit within monthly capacity.</p></div>{result && <button type="button" onClick={() => setResult(null)} className="secondary-button">Edit assumptions</button>}</header><p className="mb-6 rounded-xl border border-sky-400/15 bg-sky-400/5 p-4 text-xs leading-5 text-sky-200/70">Prototype goal data lives only in this page&apos;s current browser state and is cleared when the page/session ends. It is not permanently saved.</p>
    {result ? <Results result={result} onEditGoal={() => setResult(null)} /> : <form onSubmit={submit} className="space-y-6"><section className="onboarding-card"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><label className="block max-w-sm text-sm font-semibold text-slate-300"><span className="mb-2 block">Estimated monthly investment capacity</span><div className="goal-prefix"><span>₹</span><input type="number" min={0} required value={capacity} onChange={(event) => setCapacity(Number(event.target.value))} className="goal-input !border-0" /></div><small>Pre-filled from your profile when available.</small></label><div className="text-sm text-slate-500">Current planned total <strong className="text-slate-200">{formatRupees(goals.reduce((sum, goal) => sum + goal.planned_monthly_contribution, 0))}</strong></div></div></section>{goals.map((goal, index) => <GoalEditor key={goal.id} goal={goal} index={index} onChange={(updated) => updateGoal(index, updated)} onRemove={() => setGoals((current) => current.filter((_, itemIndex) => itemIndex !== index))} removable={goals.length > 1} />)}<button type="button" onClick={addGoal} className="secondary-button">＋ Add another goal</button><AssumptionEditor assumptions={assumptions} onChange={setAssumptions} monteCarlo={monteCarlo} setMonteCarlo={setMonteCarlo} count={simulationCount} setCount={setSimulationCount} />{error && <div role="alert" className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-4 text-sm text-rose-200">{error}</div>}<div className="flex justify-end"><button type="submit" disabled={loading} className="primary-button !px-6 !py-4 disabled:cursor-wait disabled:opacity-60">{loading ? "Running scenarios…" : "Simulate all goals"}</button></div></form>}
    <footer className="mx-auto mt-8 max-w-3xl border-t border-white/10 pt-6 text-center text-xs leading-5 text-slate-600">Hypothetical educational projections only—not forecasts, guaranteed outcomes, or regulated investment advice. Taxes, fees and product constraints are excluded.</footer></div>;
}

function Results({ result, onEditGoal }: { result: GoalSimulationResponse; onEditGoal: (id: string) => void }) { const summary = result.capacity_summary; return <div><section className={`result-card ${summary.capacity_conflicts.length ? "!border-amber-400/30" : "!border-emerald-400/20"}`}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Monthly capacity</p><h2 className="mt-1 text-3xl font-bold text-white">{formatRupees(summary.estimated_monthly_capacity)}</h2></div><div className="grid grid-cols-3 gap-5 text-sm"><Summary label="Planned" value={summary.total_planned_contributions} /><Summary label="Required" value={summary.total_required_contributions} /><Summary label="Remaining" value={summary.remaining_monthly_capacity} /></div></div>{summary.capacity_conflicts.length > 0 && <div className="mt-5 rounded-xl bg-amber-400/10 p-4"><h3 className="font-bold text-amber-200">Capacity conflict</h3><ul className="mt-2 space-y-1 text-sm text-amber-100/80">{summary.capacity_conflicts.map((item) => <li key={item}>• {item}</li>)}</ul></div>}<details className="mt-5 border-t border-white/10 pt-4"><summary className="cursor-pointer text-sm font-semibold text-slate-400">View capacity allocation order</summary><p className="mt-3 text-xs leading-5 text-slate-500">{summary.allocation_explanation}</p><div className="mt-3 space-y-2">{summary.allocations.map((item) => <div key={item.goal_id} className="flex justify-between rounded-lg bg-black/20 p-3 text-xs"><span className="text-slate-400">{item.goal_name} · {item.priority}</span><span className="text-slate-200">Assigned {formatRupees(item.assigned_monthly_capacity)} / required {formatRupees(item.required_monthly_contribution)}</span></div>)}</div></details></section><div className="mt-6 space-y-5">{result.goals.map((goal) => <div key={goal.id}><GoalResultCard goal={goal} /><button type="button" onClick={() => onEditGoal(goal.id)} className="mt-2 text-sm font-semibold text-emerald-300">Edit this goal</button></div>)}</div><details className="disclosure mt-6"><summary><span><strong>Assumptions and limitations</strong><small>Illustrative inputs and important interpretation boundaries</small></span><span>＋</span></summary><div className="grid gap-5 border-t border-white/10 p-5 md:grid-cols-2"><div>{Object.entries(result.assumptions).map(([name, values]) => <p key={name} className="mb-2 text-sm text-slate-400"><strong className="capitalize text-slate-200">{name}:</strong> {values.nominal_annual_return}% return, {values.annual_volatility}% volatility, {values.inflation_rate}% inflation</p>)}</div><ul className="space-y-2 text-xs leading-5 text-slate-500">{result.limitations.map((item) => <li key={item}>• {item}</li>)}</ul></div></details></div>; }
function Summary({ label, value }: { label: string; value: number }) { return <div><p className="text-xs text-slate-600">{label}</p><p className="mt-1 font-bold text-slate-200">{formatRupees(value)}</p></div>; }
function AssumptionEditor({ assumptions, onChange, monteCarlo, setMonteCarlo, count, setCount }: { assumptions: ScenarioAssumptions; onChange: (value: ScenarioAssumptions) => void; monteCarlo: boolean; setMonteCarlo: (value: boolean) => void; count: number; setCount: (value: number) => void }) { return <details className="disclosure"><summary><span><strong>Scenario and simulation assumptions</strong><small>Adjust these for what-if comparisons</small></span><span>＋</span></summary><div className="border-t border-white/10 p-5"><div className="grid gap-4 md:grid-cols-3">{(["conservative","base","optimistic"] as const).map((name) => <fieldset key={name} className="rounded-xl bg-black/20 p-4"><legend className="capitalize font-bold text-white">{name}</legend>{(["nominal_annual_return","annual_volatility","inflation_rate"] as const).map((field) => <label key={field} className="mt-3 block text-xs text-slate-500">{field.replaceAll("_", " ")} (%)<input type="number" min={field === "nominal_annual_return" ? -50 : 0} max={field === "inflation_rate" ? 20 : field === "annual_volatility" ? 100 : 50} step={0.5} value={assumptions[name][field]} onChange={(event) => onChange({ ...assumptions, [name]: { ...assumptions[name], [field]: Number(event.target.value) } })} className="goal-input mt-1" /></label>)}</fieldset>)}</div><div className="mt-5 flex flex-wrap items-end gap-5"><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={monteCarlo} onChange={(event) => setMonteCarlo(event.target.checked)} /> Include seeded Monte Carlo</label>{monteCarlo && <label className="text-xs text-slate-500">Generated scenarios<input type="number" min={100} max={10000} step={100} value={count} onChange={(event) => setCount(Number(event.target.value))} className="goal-input mt-1 w-36" /></label>}</div><p className="mt-4 text-xs leading-5 text-slate-600">These are hypothetical inputs, not forecasts or promised returns. Monte Carlo draws monthly returns from a normal distribution using the selected base return and volatility.</p></div></details>; }
function apiError(body: unknown): string { if (typeof body === "object" && body !== null && "detail" in body) { const detail = (body as { detail: unknown }).detail; if (Array.isArray(detail) && detail[0] && typeof detail[0] === "object" && "msg" in detail[0]) return `Please review your goals: ${String(detail[0].msg)}`; } return "Goal simulation failed. Check the API connection and inputs."; }
