import { formatRupees } from "@/lib/formatters";
import type { GoalResult } from "@/types/goals";

export function GoalResultCard({ goal }: { goal: GoalResult }) {
  const status = { already_funded: ["Already funded", "text-emerald-300 bg-emerald-400/10"], on_track: ["On track", "text-emerald-300 bg-emerald-400/10"], needs_adjustment: ["Needs adjustment", "text-amber-300 bg-amber-400/10"], currently_unfeasible: ["Currently unfeasible", "text-rose-300 bg-rose-400/10"] }[goal.status];
  return <article className="result-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-bold text-white">{goal.name}</h3><p className="mt-1 text-xs text-slate-500">{(goal.horizon_months / 12).toFixed(1)} years · {goal.category.replaceAll("_", " ")}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${status[1]}`}>{status[0]}</span></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Required monthly" value={formatRupees(goal.required_monthly_contribution)} /><Metric label="Projected value" value={formatRupees(goal.projected_value)} /><Metric label="Adjusted target" value={formatRupees(goal.inflation_adjusted_target)} /><Metric label={goal.funding_gap_or_surplus >= 0 ? "Projected surplus" : "Funding gap"} value={formatRupees(Math.abs(goal.funding_gap_or_surplus))} /></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs text-slate-500"><span>Projected attainment</span><span>{goal.projected_attainment_percentage.toFixed(1)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${Math.min(100, goal.projected_attainment_percentage)}%` }} /></div></div><div className="mt-6 grid gap-4 lg:grid-cols-[1.4fr_1fr]"><LineChart goal={goal} /><div><h4 className="text-sm font-bold text-white">Scenario comparison</h4><div className="mt-3 space-y-2">{goal.scenarios.map((scenario) => <div key={scenario.scenario} className="flex items-center justify-between rounded-xl bg-black/20 p-3 text-sm"><span className="capitalize text-slate-400">{scenario.scenario}</span><div className="text-right"><p className="font-semibold text-slate-200">{formatRupees(scenario.projected_value)}</p><p className="text-xs text-slate-600">{scenario.attainment_percentage.toFixed(0)}% of target</p></div></div>)}</div>{goal.monte_carlo && <MonteCarlo result={goal.monte_carlo} target={goal.inflation_adjusted_target} />}</div></div><details className="mt-5 border-t border-white/10 pt-4"><summary className="cursor-pointer text-sm font-semibold text-slate-400">Formulas and calculation details</summary><ul className="mt-3 space-y-2 text-xs leading-5 text-slate-500">{goal.explanations.map((item) => <li key={item}>• {item}</li>)}</ul></details></article>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-black/20 p-3"><p className="text-xs text-slate-600">{label}</p><p className="mt-1 font-bold text-slate-200">{value}</p></div>; }
function LineChart({ goal }: { goal: GoalResult }) { const sampled = goal.timeline.filter((_, index) => index % Math.max(1, Math.floor(goal.timeline.length / 24)) === 0 || index === goal.timeline.length - 1); const max = Math.max(goal.inflation_adjusted_target, ...sampled.map((point) => point.projected_value), 1); const points = sampled.map((point, index) => `${(index / Math.max(1, sampled.length - 1)) * 100},${100 - (point.projected_value / max) * 90}`).join(" "); const targetY = 100 - (goal.inflation_adjusted_target / max) * 90; return <figure><figcaption className="mb-3 text-sm font-bold text-white">Base-scenario future value</figcaption><svg role="img" aria-label={`Projected value timeline for ${goal.name}`} viewBox="0 0 100 105" className="h-52 w-full rounded-xl bg-black/20 p-3" preserveAspectRatio="none"><line x1="0" x2="100" y1={targetY} y2={targetY} stroke="#64748b" strokeDasharray="3 3" vectorEffect="non-scaling-stroke" /><polyline fill="none" stroke="#34d399" strokeWidth="2" points={points} vectorEffect="non-scaling-stroke" /></svg><div className="mt-2 flex justify-between text-xs text-slate-600"><span>Today</span><span>Target: {formatRupees(goal.inflation_adjusted_target)}</span><span>{(goal.horizon_months / 12).toFixed(1)}y</span></div></figure>; }
function MonteCarlo({ result, target }: { result: NonNullable<GoalResult["monte_carlo"]>; target: number }) { const max = Math.max(result.p90, target, 1); return <div className="mt-5 border-t border-white/10 pt-4"><h4 className="text-sm font-bold text-white">Generated-scenario range</h4><div className="mt-3 space-y-2">{[["P10",result.p10],["P50",result.p50],["P90",result.p90]].map(([label, value]) => <div key={String(label)} className="grid grid-cols-[2rem_1fr_auto] items-center gap-2 text-xs"><span className="text-slate-500">{label}</span><div className="h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-sky-400" style={{ width: `${(Number(value) / max) * 100}%` }} /></div><span className="text-slate-300">{formatRupees(Number(value))}</span></div>)}</div><p className="mt-3 text-xs leading-5 text-slate-500"><strong className="text-slate-300">{result.attainment_frequency_percentage.toFixed(1)}%</strong> — {result.attainment_frequency_label}</p></div>; }
